name: CI

on:
  push:
    branches:
    - "**"

env:
  REGISTRY: "quay.io"
  IMAGE_NAME: travelping/fpp-vpp
  # this points to buildkitd k8s service
  BUILDKITD_ADDR: tcp://buildkitd:1234

jobs:
  build:
    runs-on:
    - ubuntu-22.04
    strategy:
      matrix:
        build_type: [debug, release]
    env:
      QUAY_USER_ID: ${{ secrets.QUAY_USER_ID }}
      QUAY_TOKEN: ${{ secrets.QUAY_TOKEN }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Prepare repo
      run: |
        git config --global user.email "dummy@example.com"
        git config --global user.name "dummy user"
        hack/update-vpp.sh
    - name: Login to quay.io
      uses: docker/login-action@v1
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.QUAY_USER_ID }}
        password: ${{ secrets.QUAY_TOKEN }}
    - name: Build fpp-vpp image
      run: |
        BUILD_TYPE="${{ matrix.build_type }}" hack/ci-build.sh
        mv /tmp/_out _out
    - name: Upload debs
      uses: actions/upload-artifact@v2
      with:
        name: debs-${{ matrix.build_type }}
        path: _out/*
    - name: Upload image.txt
      uses: actions/upload-artifact@v2
      with:
        name: image-${{ matrix.build_type }}
        path: image-${{ matrix.build_type }}.txt
    - name: Upload image.txt for the dev image
      uses: actions/upload-artifact@v2
      with:
        name: image-dev-${{ matrix.build_type }}
        path: image-dev-${{ matrix.build_type }}.txt

  # dummy job for release.yaml to wait on
  conclude:
    runs-on:
    - ubuntu-22.04
    needs:
    - build
    steps:
    - name: Dummy step
      run: echo ok
