name: Release

on:
  push:
    tags: ["v*"]

jobs:
  retag-base-image:
    runs-on:
      - ubuntu-24.04

    strategy:
      matrix:
        build_type: [debug, release]

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          # for git describe
          fetch-depth: 0

      - name: Prepare repo
        run: |
          git config --global user.email "dummy@example.com"
          git config --global user.name "dummy user"

      - name: Login to the registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9 # v3
        with:
          registry: ${{ vars.REGISTRY_DOMAIN }}
          username: ${{ secrets.QUAY_USER_ID }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Ensure base image to retag is present
        id: ensure-base-image-to-retag
        run: |
          BUILD_TYPE="${{ matrix.build_type }}" BASE_REPO="${{ vars.BASE_REPO }}" build/ensure-base-image-to-retag.sh

      - name: Retag base image
        if: steps.ensure-base-image-to-retag.outputs.image_to_retag_present == 'true'
        run: |
          BUILD_TYPE="${{ matrix.build_type }}" BASE_REPO="${{ vars.BASE_REPO }}" build/retag-base-image.sh

    outputs:
      debug_image_to_retag_present: ${{ steps.ensure-base-image-to-retag.outputs.debug_image_to_retag_present }}
      release_image_to_retag_present: ${{ steps.ensure-base-image-to-retag.outputs.release_image_to_retag_present }}

  rebuild-and-tag-base-release-image:
    needs: retag-base-image
    if: needs.retag-base-image.outputs.release_image_to_retag_present == 'false'
    uses: ./.github/workflows/build-images.yaml
    with:
      build_type: release
    secrets: inherit

  rebuild-and-tag-base-debug-image:
    needs: retag-base-image
    if: needs.retag-base-image.outputs.debug_image_to_retag_present == 'false'
    uses: ./.github/workflows/build-images.yaml
    with:
      build_type: debug
    secrets: inherit

  changelog:
    runs-on:
      - ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5
        with:
          fetch-depth: 0

      - name: Build Changelog
        id: build_changelog
        uses: mikepenz/release-changelog-builder-action@c9dc8369bccbc41e0ac887f8fd674f5925d315f7 # v5
        with:
          configuration: "changelog-config.json"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post the release
        uses: softprops/action-gh-release@a06a81a03ee405af7f2048a818ed3f03bbf83c7b # v2
        with:
          body: ${{ steps.build_changelog.outputs.changelog }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
